export const PRODUCT_LIST_REQUEST2 = 'PRODUCT_LIST_REQUEST2';
export const PRODUCT_LIST_SUCCESS2 = 'PRODUCT_LIST_SUCCESS2';
export const PRODUCT_LIST_FAIL2 = 'PRODUCT_LIST_FAIL2';

export const PRODUCT_DETAILS_REQUEST2 = 'PRODUCT_DETAILS_REQUEST2';
export const PRODUCT_DETAILS_SUCCESS2 = 'PRODUCT_DETAILS_SUCCESS2';
export const PRODUCT_DETAILS_FAIL2 = 'PRODUCT_DETAILS_FAIL2';

export const PRODUCT_SAVE_REQUES2 = 'PRODUCT_SAVE_REQUEST2';
export const PRODUCT_SAVE_SUCCESS2 = 'PRODUCT_SAVE_SUCCESS2';
export const PRODUCT_SAVE_FAIL2 = 'PRODUCT_SAVE_FAIL2';

export const PRODUCT_DELETE_REQUEST2 = 'PRODUCT_DELETE_REQUEST2';
export const PRODUCT_DELETE_SUCCESS2 = 'PRODUCT_DELETE_SUCCESS2';
export const PRODUCT_DELETE_FAIL2 = 'PRODUCT_DELETE_FAIL2';

export const PRODUCT_REVIEW_SAVE_REQUEST2 = 'PRODUCT_REVIEW_SAVE_REQUEST2';
export const PRODUCT_REVIEW_SAVE_SUCCESS2 = 'PRODUCT_REVIEW_SAVE_SUCCESS2';
export const PRODUCT_REVIEW_SAVE_FAIL2 = 'PRODUCT_REVIEW_SAVE_FAIL2';
export const PRODUCT_REVIEW_SAVE_RESET2 = 'PRODUCT_REVIEW_SAVE_RESET2';
